Document = {
	SOI ~ (Title | Paragraph | NEWLINE)+ ~ EOI
}

Title = @{
	"#"+ ~ (!NEWLINE ~ ANY)* ~ &NEWLINE?
}

Paragraph = {
	(Word | Time)+ ~ &NEWLINE?
}

Word = @{
    (LETTER+ ~ ("'" ~ LETTER+)?) | (LETTER+ ~ ("-" ~ LETTER+)+)
}

Time = @{
    NUMBER+ ~ ":" ~ NUMBER+
}

// Pest supports these rules implicitly when defined
COMMENT = _{
    "<!--" ~ (!"-->" ~ ANY)* ~ "-->"
}

WHITESPACE = _{
    " " | "," | "." | "!" | "?" | "*" | "-" | "—" | ":" | ";" | "'" | "\""
}
